version: "3.3"
services:
  loki:
    image: grafana/loki:2.7.3
    user: 0:0
    volumes:
      - ./data:/loki # swarm模式记得修改
      - ./loki.yaml:/etc/loki  # swarm模式记得修改这里
    ports:
      - "3100:3100"
      - "7946"
    command: "-config.file=/etc/loki/loki.yaml"
    restart: always
