- job_name: 'blackbox'
  metrics_path: /probe
  scrape_interval: 30s
  scheme: http
  # file_sd_configs:
  #   - files:
  #     - /etc/prometheus/sd/blackbox.yaml
  static_configs:
  - targets:
    - monitor_blackbox:9115:_:http_2xx:_:hangzhou:_:wtm7s8:_:http://www.baidu.com/  # update your monitor here

  relabel_configs:
    # adds "module" label in the final labelset
    - source_labels: [__address__]
      regex: '.*:_:(.*):_:.*:_:.*:_:.*'
      target_label: module
    # adds "geohash" label in the final labelset
    - source_labels: [__address__]
      regex: '.*:_:.*:_:.*:_:(.*):_:.*'
      target_label: geohash
    # rewrites "instance" label with corresponding URL
    - source_labels: [__address__]
      regex: '.*:_:.*:_:.*:_:.*:_:(.*)'
      target_label: instance
    # rewrites "pop" label with corresponding location name
    - source_labels: [__address__]
      regex: '.*:_:.*:_:(.*):_:.*:_:.*'
      target_label: pop
    # passes "module" parameter to Blackbox exporter
    - source_labels: [module]
      target_label: __param_module
    # passes "target" parameter to Blackbox exporter
    - source_labels: [instance]
      target_label: __param_target
    # the Blackbox exporter's real hostname:port
    - source_labels: [__address__]
      regex: '(.*):_:.*:_:.*:_:.*:_:.*'
      target_label: __address__